package com.main.app.message;

import java.time.LocalDateTime;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.amqp.rabbit.annotation.RabbitListener;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.messaging.Message;
import org.springframework.messaging.handler.annotation.Payload;
import org.springframework.stereotype.Component;

import com.main.app.service.PaymentService;

@Component
public class PaymentResponseErrorConsumer {
	
	private static Logger log = LoggerFactory.getLogger(PaymentResponseErrorConsumer.class);
	
	@Autowired
	private PaymentService payment;
	
	@RabbitListener(queues={"payment-response-error-queue"})
	public void receive(@Payload Message<?> message) {
		System.out.println(" ===== [FAILURE MESSAGE] PRODUCER CONSUMING A RANDOM RESPONSE TEST MESSAGE GENERATED BY PaymentRequestConsumer.java WORKER ===== ");
		log.info("Message " + message + " " + LocalDateTime.now());
		String payload = String.valueOf(message.getPayload());
		payment.paymentError(payload);
	}
	
}
