version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: "rabbitmq"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
        # AMQP protocol port
        - "5672:5672"
        # HTTP management UI
        - "15672:15672"
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq
        - rabbitmq_log:/var/log/rabbitmq
    networks:
      - my-network
networks:
  my-network:
      name: my-network
      external: true
volumes:
  rabbitmq_data:
  rabbitmq_log:
